// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPyfAQ_GxT8916gpRVZWcrTiBQ44F_U3c',
    appId: '1:23680641155:web:ddd8745b4dd5d8354053b6',
    messagingSenderId: '23680641155',
    projectId: 'ecommerce-demo-9fa8b',
    authDomain: 'ecommerce-demo-9fa8b.firebaseapp.com',
    storageBucket: 'ecommerce-demo-9fa8b.appspot.com',
    measurementId: 'G-44ZM8LN63L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-wnLofPPPa05p1elQSahT4rk2-OPPG_M',
    appId: '1:23680641155:android:50f4b511865523774053b6',
    messagingSenderId: '23680641155',
    projectId: 'ecommerce-demo-9fa8b',
    storageBucket: 'ecommerce-demo-9fa8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUroErN43desd5-OCnB1JZl4v180fjfIk',
    appId: '1:23680641155:ios:b0c0616dc227b9a24053b6',
    messagingSenderId: '23680641155',
    projectId: 'ecommerce-demo-9fa8b',
    storageBucket: 'ecommerce-demo-9fa8b.appspot.com',
    iosClientId: '23680641155-lfj680jcp30bfeuf0k7ihi057obli9g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUroErN43desd5-OCnB1JZl4v180fjfIk',
    appId: '1:23680641155:ios:b0c0616dc227b9a24053b6',
    messagingSenderId: '23680641155',
    projectId: 'ecommerce-demo-9fa8b',
    storageBucket: 'ecommerce-demo-9fa8b.appspot.com',
    iosClientId: '23680641155-lfj680jcp30bfeuf0k7ihi057obli9g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceDemo',
  );
}
